### PR TITLE
feat: add support for container pull policies

### PR DESCRIPTION
**Pull request by jbrockopp**
Part of the effort for go-vela/community#104

[Previously](https://github.com/go-vela/types/pull/107), 4 different pull policies were introduced:

* `always` - used to always pull the image
* `not_present` - used to only pull the image if it doesn't already exist
* `on_start` - used to only pull the image before the container starts
* `never` - used to never pull the image

The `not_present` policy will be the default if one is not provided.

This adds support for those different pull policies 👍

### CODE REVIEW

**Comment by jbrockopp** [comment]
Waiting for https://github.com/go-vela/pkg-runtime/pull/56 before I can request a review on this 👍

**Comment by jbrockopp** [comment]
Waiting for https://github.com/go-vela/pkg-runtime/pull/57 before I can request a review on this 👍

**Review by davidvader — DISMISSED** [review]
LGTM :)

**Review by meinenec — APPROVED** [review]

**Review by kneal — APPROVED** [review]
LGTM 🐬

**Pull request merged**
